# Word Embeddings

from https://ashutoshtripathi.com/2020/09/04/word2vec-and-semantic-similarity-using-spacy-nlp-spacy-series-part-7/

In [1]:
!python -m spacy download en_core_web_md

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 MB 15.5 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [2]:
import spacy
nlp = spacy.load('en_core_web_md')

In [3]:
nlp(u'king').vector

array([-1.1296e-01, -4.1865e+00, -1.8453e+00,  3.0781e-01,  2.4956e+00,
        9.6267e-01, -1.8161e+00,  4.4655e+00, -2.8210e+00,  9.7090e-01,
        1.3542e+01,  4.3195e-01, -5.3098e+00,  4.7098e+00,  2.9030e+00,
        1.5588e+00,  6.0064e+00, -3.0345e+00,  1.0626e+00, -7.7197e-01,
       -5.4771e+00, -9.7380e-01, -4.4345e+00,  5.8367e+00,  2.4302e+00,
       -3.9408e+00, -9.1862e-01, -4.9124e+00,  1.4591e+00, -7.2772e-01,
        3.4957e+00, -4.0077e+00, -1.8354e+00, -4.1052e+00,  4.9211e+00,
       -9.7053e-01,  1.9223e+00,  5.2605e+00,  1.6086e+00,  7.1328e-01,
       -1.2146e+00, -1.9869e+00,  8.0265e-01,  2.9298e+00,  7.2985e-01,
       -6.2892e-01, -1.7082e+00,  1.9893e+00,  4.7529e-01,  3.2264e+00,
       -3.9215e+00,  4.6556e+00,  1.3475e+00, -1.0979e+00, -3.0365e+00,
        1.5815e+00,  2.2835e+00, -4.0616e+00,  2.5730e+00,  4.0618e+00,
        9.5438e-01, -6.2563e+00,  5.6463e+00, -3.8933e+00,  4.4076e+00,
        2.0517e+00, -6.6906e+00, -6.9448e+00,  6.0371e+00,  9.30

In [4]:
king= nlp(u'king').vector
len(king)

300

In [5]:
doc = nlp('the king of the jungle is the lion')
doc.vector

array([-2.93455744e+00,  5.25377512e-01,  8.35605025e-01,  6.44618869e-01,
        7.39411259e+00,  1.18750602e-01, -5.08512706e-02,  5.04100037e+00,
        2.89796376e+00, -5.87882578e-01,  1.07523355e+01,  1.71863234e+00,
       -5.11190748e+00,  1.97471499e+00,  9.58687663e-02,  4.87642527e+00,
        2.96165133e+00,  1.78971744e+00,  4.44482505e-01, -3.30083609e+00,
       -6.65769994e-01, -1.94370008e+00, -2.60657239e+00,  2.87815738e+00,
        1.54720867e+00, -2.38309503e-01, -1.77926505e+00, -4.04381275e+00,
        2.15653747e-01,  2.27415729e+00,  8.14487457e-01, -6.89626336e-02,
       -1.34750628e+00, -6.01103163e+00, -2.85438776e+00, -5.73503852e-01,
       -1.16957617e+00,  4.92072487e+00,  1.15580261e+00,  1.07927251e+00,
       -9.02361214e-01,  1.62621248e+00, -5.75981319e-01,  1.07423496e+00,
       -2.54548144e+00,  1.79596102e+00,  1.11764002e+00, -1.38787478e-01,
       -1.65709972e-01, -5.08681297e-01, -2.38249755e+00,  5.62556219e+00,
        1.23622727e+00, -

In [6]:
doc = nlp(u'lion cat pet')

for token1 in doc:
    for token2 in doc:
      print(token1.text, token2.text, token1.similarity(token2))


lion lion 1.0
lion cat 0.3854507803916931
lion pet 0.20031584799289703
cat lion 0.3854507803916931
cat cat 1.0
cat pet 0.732966423034668
pet lion 0.20031584799289703
pet cat 0.732966423034668
pet pet 1.0


In [8]:
  from scipy import spatial
  def cosine_similarity(v1,v2):
    return 1 - spatial.distance.cosine(v1,v2)

In [13]:
king = nlp.vocab['paris'].vector
man = nlp.vocab['france'].vector
woman = nlp.vocab['italy'].vector
queen = nlp.vocab['queen'].vector

In [14]:
new_vector = king - man + woman

computed_similarities = []

for word in nlp.vocab:
  if word.has_vector and word.is_lower and word.is_alpha:
    similarity = cosine_similarity(new_vector,word.vector)
    computed_similarities.append((word,similarity))


In [15]:
computed_similarities = sorted(computed_similarities,key=lambda item: -item[1])


In [16]:
print([ w[0].text for w in computed_similarities[:5]])

['paris', 'italy', 'was', 'where', 'y']


## using pymagnitude

In [ ]:
# install pymagnitude
!pip install pymagnitude

In [ ]:
# play with vectors
import numpy as np

The history saving thread hit an unexpected error (DatabaseError('database disk image is malformed')).History will not be written to the database.


In [ ]:
v1 = np.array([1,0,0])
# scalar multiplication
v2 = v1 * 2

In [ ]:
v2

array([2, 0, 0])

In [ ]:
# vectors multiplication
v2 * v2

array([4, 0, 0])

In [ ]:
np.dot(v1,v2)

2

In [ ]:
np.array([1] + [0 for i in range(299)])

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr1 = [0 for i in range(300)]
arr1[5] = 1
np.array(arr1)

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.arange(2.0,3.0,0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
from numpy.linalg import norm
norm(np.array([1,0,0]))

1.0

In [ ]:
norm(np.array([1,1]))

1.4142135623730951

In [ ]:
from math import sqrt
sqrt(2.0)

1.4142135623730951

### word embeddings
Download pre-trained vector models from [https://github.com/plasticityai/magnitude#pre-converted-magnitude-formats-of-popular-embeddings-models](https://github.com/plasticityai/magnitude#pre-converted-magnitude-formats-of-popular-embeddings-models)

In [ ]:
!pip install pymagnitude

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 4.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pymagnitude: filename=pymagnitude-0.1.143-cp310-cp310-linux_x86_64.whl size=5675779783 sha256=4002ce12c569393391998e28ebf0172069617a477e5e5697a75999dd5bc1fcf9
  Stored in directory: /root/.cache/pip/wheels/a4/4c/57/c86621be56d6005aea172c6700671ffa003bb69ad17d724555
Successfully built pymagnitude


In [ ]:
from pymagnitude import Magnitude

ModuleNotFoundError: No module named 'pymagnitude'

In [ ]:
vectors = Magnitude('GoogleNews-vectors-negative300.magnitude')

In [ ]:
vectors.query('king')

array([ 4.340640e-02,  1.026280e-02,  2.965300e-03,  4.811720e-02,
       -8.832700e-03, -1.244990e-02,  3.852740e-02, -6.830620e-02,
        1.766540e-02,  1.251719e-01, -8.344790e-02, -1.043099e-01,
       -6.124000e-02, -8.580300e-03, -5.787520e-02, -5.854810e-02,
        1.194520e-02,  1.798100e-03,  1.598300e-02,  4.441580e-02,
        4.710770e-02,  3.886390e-02,  2.052550e-02,  4.710770e-02,
        3.482610e-02, -6.090350e-02, -8.681280e-02,  2.060960e-02,
        1.177693e-01, -1.072540e-02,  3.600370e-02,  2.128260e-02,
        4.290170e-02,  1.379583e-01, -1.110396e-01,  2.893760e-02,
        1.345930e-02,  2.018900e-03,  2.422680e-02,  5.955760e-02,
        4.778070e-02, -7.974660e-02,  9.758020e-02,  4.912660e-02,
        1.177693e-01, -8.243800e-03, -3.785440e-02,  1.144040e-02,
       -1.884310e-02,  5.278600e-03, -5.585630e-02,  5.451030e-02,
       -8.950460e-02,  6.940000e-03, -5.619280e-02,  4.679000e-04,
       -4.979960e-02, -1.960020e-02,  1.480530e-02, -8.496200e

In [ ]:
'maurizio' in vectors

False

In [ ]:
vectors.query('maurizio')

array([-0.01337742,  0.0633055 , -0.0113367 ,  0.06595497,  0.01176116,
       -0.03198689, -0.01784704, -0.04235846, -0.024914  ,  0.06368731,
       -0.02650721,  0.03564478, -0.02790918, -0.02985081, -0.03738907,
        0.09176725,  0.09036016, -0.0500975 ,  0.05354859,  0.07229868,
        0.001998  , -0.03952503,  0.16273913, -0.04384092,  0.02636628,
       -0.06363992,  0.04390427,  0.09698918, -0.068953  ,  0.02755391,
        0.02351016,  0.0043479 ,  0.11495978,  0.06435223,  0.04374289,
       -0.09928042, -0.05293204,  0.01903162, -0.04116889, -0.07623796,
       -0.03970936,  0.06756437, -0.0276115 ,  0.01783836,  0.0451994 ,
       -0.01288719, -0.0331281 ,  0.11572005, -0.01016764,  0.05186079,
       -0.08413151,  0.12546207,  0.03493756, -0.05296758, -0.02770761,
        0.17458827,  0.02834679, -0.07635037, -0.05726126, -0.01987499,
       -0.06595363,  0.09206444,  0.03314623, -0.06025568,  0.04710418,
       -0.08997549, -0.00649255, -0.0523768 ,  0.07005617, -0.02

In [ ]:
v_king , v_queen = vectors.query('king') , vectors.query('queen')
np.dot( v_king , v_queen )

0.65109575

In [ ]:
from scipy.spatial.distance import cosine
cosine( v_king , v_queen )

0.34890425205230713

In [ ]:
len(vectors)

3000000

In [ ]:
len(v_king)

300

In [ ]:
vectors.most_similar('king')  # KNN  k-nearest neighbours (k=10)

[('kings', 0.7138046),
 ('queen', 0.65109575),
 ('monarch', 0.6413195),
 ('crown_prince', 0.620422),
 ('prince', 0.61599934),
 ('sultan', 0.58648247),
 ('ruler', 0.57975674),
 ('princes', 0.5646552),
 ('Prince_Paras', 0.5432944),
 ('throne', 0.54221046)]

In [ ]:
vectors.most_similar(positive=['Rome','France'] , negative=['Italy'])

[('Paris', 0.7190687),
 ('French', 0.5460343),
 ('Avignon', 0.53562486),
 ('Hopital_Europeen_Georges_Pompidou', 0.52362144),
 ('Strasbourg', 0.52201957),
 ('Brussels', 0.5087737),
 ('Pantheon_Sorbonne', 0.50093627),
 ('Reims', 0.5001292),
 ('Poitiers', 0.49561858),
 ('Rheims', 0.48938447)]

In [ ]:
vectors.most_similar(positive=['Rome','Spain'] , negative=['Italy'])

[('Madrid', 0.69315314),
 ('Seville', 0.58928794),
 ('Barcelona', 0.5854126),
 ('Athens', 0.5166985),
 ('Seville_Spain', 0.5157975),
 ('Giles_Tremlett', 0.5132016),
 ('Santiago_de_Compostela', 0.51311743),
 ('Valencia', 0.5016351),
 ('Spaniards', 0.4990644),
 ('Paris', 0.48526046)]

In [ ]:
vectors.most_similar(positive=['doctor','woman'] , negative=['man']) # this is showing some bias man/woman in this model

[('gynecologist', 0.7093892),
 ('nurse', 0.64772856),
 ('doctors', 0.6471461),
 ('physician', 0.6438996),
 ('pediatrician', 0.6249488),
 ('nurse_practitioner', 0.62183136),
 ('obstetrician', 0.6072015),
 ('ob_gyn', 0.5986713),
 ('midwife', 0.59270644),
 ('dermatologist', 0.57395685)]